name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gnupg gnupg1 gpgv1 debsig-verify createrepo-c dnf rpm curl gettext-base monkeysphere libtool libssl-dev libbz2-dev libbsd-dev libarchive-dev liblzma-dev zlib1g-dev
          mkdir /tmp/pkg
          cd /tmp/pkg
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.18.0
          curl -L -o pkg.zip https://github.com/freebsd/pkg/archive/refs/tags/1.17.5.zip
          unzip -qo pkg.zip
          cd pkg-1.17.5
          ./configure
          make -s -j$(nproc)
          sudo make install
          rm -rf /tmp/pkg
      - name: Release Packages
      # TODO: Remove git config step later once the repo https://github.com/nginxinc/crossplane-go is made public
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          NFPM_SIGNING_KEY_FILE: ${{ secrets.INDIGO_GPG_AGENT }}
        run: |
          git config --global url."https://dhurley:${TOKEN}@github.com".insteadOf "https://github.com"
          make package
        #   make release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nginx-agent
          path: build/packages/nginx-agent.tar.gz
          retention-days: 3
